### ISSUE TITLE
Files created in system tmp dir are not cleaned up

### ISSUE THREAD

**Issue by ghost** [daisy/pipeline-issues#263]
_From [john.bru...@gmail.com](https://code.google.com/u/108810182039435316737/) on December 20, 2012 22:15:54_

What steps will reproduce the problem? 1. Run a file through a conversion such as dtbook-to-epub3
2. Check the contents of the system tmp directory (e.g. /tmp on Linux) for a zip file starting with "p2ws" and followed by a long number.
3. The contents of the zip appear to be original DAISY book package What is the expected output? What do you see instead? I would like to see these files cleaned out of tmp when the conversion process no longer needs them. For a long running service, this can fill up a tmp volume. What version of the product are you using? On what operating system? 1.4 on Linux Please provide any additional information below. We are working around this for the moment with a cron job that runs every hour and deletes things from /tmp that are at least 24 hours old.

_Original issue: http://code.google.com/p/daisy-pipeline/issues/detail?id=263_

**Comment by capitancambio** [comment]
I believe this is a won't fix (these files are deleted when rebooting) otherwise it would be responsibility of the sysadmin, I presume
