### ISSUE TITLE
WebUI: Dynamic validation of script arguments

### ISSUE THREAD

**Issue by ghost** [daisy/pipeline-issues#285]
_From [josteinaj@gmail.com](https://code.google.com/u/josteinaj@gmail.com/) on March 27, 2013 13:48:10_

The Web UI now supports dynamic validation of forms. The validation is performed server-side in the form models.

Validation of script arguments will be implemented in pipeline-clientlib-java.

_Original issue: http://code.google.com/p/daisy-pipeline/issues/detail?id=285_

**Comment by josteinaj** [comment]
moved issue to webui repo to keep all webui-specific issues together
