### ISSUE TITLE
Web UI: support custom data types in drop-down and multiple-choice lists

### ISSUE THREAD

**Issue by ghost** [daisy/pipeline-issues#331]
_From [josteinaj@gmail.com](https://code.google.com/u/josteinaj@gmail.com/) on June 20, 2013 16:02:54_

We have discussed custom XSD datatypes, and they are becoming more relevant as we start implementing support for TTS.

The Web UI should be ready for this.

Custom XSD Datatypes: http://code.google.com/p/daisy-pipeline/wiki/ScriptMetadataCleanup#Custom_XSD_Data_Types

_Original issue: http://code.google.com/p/daisy-pipeline/issues/detail?id=331_

**Comment by bertfrees** [comment]
see https://github.com/daisy/pipeline-framework/pull/84

**Comment by josteinaj** [comment]
This issue was moved to daisy/pipeline-webui#42
