### ISSUE TITLE
failing to upload some ZIP in the webui

### ISSUE THREAD

**Issue by ghost** [daisy/pipeline-issues#373]
_From [rdeltour@gmail.com](https://code.google.com/u/rdeltour@gmail.com/) on December 13, 2013 15:10:32_

Seems to happen when the ZIP has entries with combining unicode characters.

Romain can provide a ZIP that fails systematically.

_Original issue: http://code.google.com/p/daisy-pipeline/issues/detail?id=373_

**Comment by josteinaj** [comment]
I'm closing this issue. Feel free to open it again if it is still an issue.
