### ISSUE TITLE
Jobs can stay IDLE when run in parallel

### ISSUE THREAD

**Issue by rom1mouret** [daisy/pipeline-issues#425]
When 3 jobs are run in parallel with 3 clients, one of the clients notifies us that the job is in IDLE state:

```
[DP2] Job with id 6bb67552-4b50-4f5b-84a0-a70f828c720f submitted to the server
[DP2] IDLE
```

Then the client exits. Is that a feature or a bug?

From what I understand of the framework, it seems like IDLE is the default status. It is changed to RUNNING after the framework does its business. If the WS sends the job's status to the client before it gets changed to RUNNING, we run into trouble.

I've seen it with 2 jobs, but quite infrequently.

The pipeline version I am using:
[https://github.com/daisy/pipeline-assembly/tree/java_8](https://github.com/daisy/pipeline-assembly/tree/java_8)

The client command:
```
./dp2 dtbook-to-zedai --i-source AreYouReadyV3.xml -o /tmp/test.zip
```

My system:
Ubuntu 12.04 32 bits

Nothing of interest in the server's logs.

**Comment by rdeltour** [comment]
Closing this since we're now using the Go CLI. Please reopen if the problem persists.
