### ISSUE TITLE
Log the exceptions thrown by Declarative Services

### ISSUE THREAD

**Issue by rom1mouret** [daisy/pipeline-issues#437]
Is there a way to configure the Pipeline so that any exception thrown by DS activations or DS constructors are logged to the main log file?

For instance:
```Java
@Activate
void activate(ComponentContext ctx) {
     throw new Exception("Where am I?");
}
```

I read somewhere that SCR catches those exceptions and tries to log them, but I can't find a way to enable this feature.

**Comment by capitancambio** [comment]
https://code.google.com/p/osgi-logging/wiki/OSGiLogging might become helpful

**Comment by capitancambio** [comment]
It's done over some branches in pipeline-assembly pipeline-framework and osgi-libs. It triggered the log of a osgi related exception when bringing up the persistence unit, osgi might retry later as the persistence unit and the logging ends up working fine. It's more a cosmetic issue.

**Comment by capitancambio** [comment]
https://github.com/daisy/osgi-libs/pull/31
https://github.com/daisy/pipeline-framework/pull/92
https://github.com/daisy/pipeline-assembly/pull/80

**Comment by bertfrees** [comment]
I think this one can be closed?

**Comment by capitancambio** [comment]
aye, cheers
