### ISSUE TITLE
nav.xhtml: navigation document (title page)

### ISSUE THREAD

**Issue by dtbook** [daisy/pipeline-issues#439]
[nordic_nav_references_1] The text for the heading in the navigation document ("Titlepage") should match the headline in the content document ("Varm tass i mörkret" at DTB15689-2-titlepage.xhtml#level1_2)_(Technofunda_Partha)

**Comment by josteinaj** [comment]
moved issue to nlbdev/nordic-epub3-dtbook-migrator#265
