### ISSUE TITLE
Make all messages coming from common-utils and scripts-utils have "DEBUG" severity.

### ISSUE THREAD

**Issue by josteinaj** [daisy/pipeline-issues#442]
This allows for cleaner executions logs in UIs.

**Comment by josteinaj** [comment]
related issue: #443

**Comment by bertfrees** [comment]
(see also [Pipeline 2 F2F Nancy](https://docs.google.com/document/d/1JXBLzXr3WldLiNDkmZd7gdGITuZyLAgeddf7gO9lQbY#bookmark=id.rq0mjjpxwhmz))

**Comment by josteinaj** [comment]
Can be closed when these are merged:
daisy/pipeline-modules-common#81
daisy/pipeline-scripts-utils#76
daisy/pipeline-mod-tts#53
