### ISSUE TITLE
Progress indicator for jobs

### ISSUE THREAD

**Issue by josteinaj** [daisy/pipeline-issues#445]
We discussed this at the beginning of the project I think, and decided that it would be too difficult to calculate progress.

I think [we should reconsider](http://www.nngroup.com/articles/progress-indicators/).

It would be up to the script author to determine how to calculate the progress.

For instance, we could have a convention where we put a percentage in the execution messages as `[\d+%]`, and do stuff like this:
```xml
<px:message message="[$1%] Processing file $2 of $3">
    <p:with-option name="param1" select="10 + floor((p:iteration-position() div $count) * 20)"/>
    <p:with-option name="param2" select="p:iteration-position()"/>
    <p:with-option name="param3" select="$count"/>
</px:message>
```
(...which would output percentages in the range from 10% to 30%)

We could also have an attribute on px:message, or maybe a separate step, for reporting progress.

The client can then choose to interpret that and display for instance a progressbar.

**Comment by rdeltour** [comment]
I agree that it w/b a great usability improvement. This is a difficult feature to design/implement however, especially when it gets to informing the user of the overall progress of a script based on several modular (sometimes deeply nested) steps.

Another potential approach is to introduce a kind of "unit of progress" and script authors would estimate when to report the consumption of such units. (e.g. one quick XSLT consumes 1 unit vs speaking a 10k text with TTS consumes 20 units)... I'm just writing off the top of my head, we need to figure out an approach that can be reasonably accurate and simple to use by script authors.

**Comment by josteinaj** [comment]
Good idea.

So how about this:

The Pipeline 2 script would contain `[work remaining]` statements:
```xml
<px:message message="[work remaining] 100"/>
<px:step1/>
<px:message message="[work remaining] 80"/>
<px:step2/>
<px:message message="[work remaining] 20"/>
<px:step3/>
```

The script steps (such as `px:step1` in the example) would contain `[work completed]` statements:
```xml
<px:message message="[work completed] 3"
```

Steps not invoked directly from Pipeline 2 scripts (such as utility steps) would not contain work statements. We would need to take care that script steps do not invoke eachother as well (as that would mess up the progress); they should only be invoked from Pipeline 2 scripts (which I think is always the case anyway).

The client would set its progressbar at "total work completed" / ("total work completed at last work remaining statement" + "work remaining").

The message statements would have DEBUG severity to avoid making them visible to the user; they could also be filtered by the client. We would not need to modify anything in the engine.

Do you think that could work?

**Comment by josteinaj** [comment]
I've been thinking a bit about this and I'm currently thinking about this approach:

The progress can be declared in `px:message` statements by starting the message with:

`[progress my-name FROM-TO sub-name]`

- `FROM` and `TO` are integers in the range `[0,100]`.
- `my-name` and `sub-name` would typically mirror the step name, so you might have
  `dtbook-to-pef.convert`, `fileset-load`, `dtbook-validate.validate` and so on.
- The main scripts would not have a `my-name` to signal that they are the "top level"
  progress statements.
- `sub-name` would be optional but recommended as it allows for calculating the
  progress of sub-processes/steps.
- The progress within the range `FROM`-`TO` would be filled by progress
  statements with the name `sub-name`. So if you have `[progress 40-80 convert]` in
  the main script, then the progress statement `[progress convert 30-50]` would
  signal that the job are 52% done (40% + 30% * (80% - 40%)).
- The integers `FROM` and `TO` can be calculated based on the size of the input document,
  or any other desired metric, by using `<p:with-option name="message" select="..."/>`
  on the message step if desired.

The client would filter out `\[progress[^\]*\] *` before displaying the messages, and could calculate the percentage. Unless we do it in the engine of course, but I expect we want to do this in the clients.

If nobody objects, I might try implementing this in the Web UI in the not to far future.

## Example

dtbook-to-pef.xpl
```xml
<p:declare-step type="px:dtbook-to-pef" ...>
(...)

<px:message message="[progress 0-40 dtbook.load] Converting from DTBook to PEF"/>
<px:dtbook.load>
  (...)
</px:dtbook.load>

<px:message message="[progress 40-80 dtbook-to-pef.convert] Converting from DTBook to PEF"/>
<px:dtbook-to-pef.convert>
  (...)
</px:dtbook-to-pef.convert>

<px:message message="[progress 80-100 pef.store] Converting from DTBook to PEF"/>
<px:pef.store>
  (...)
</px:pef.store>

</p:declare-step>
```

dtbook-to-pef.convert.xpl
```xml
<p:declare-step type="px:dtbook-to-pef.convert" ...>
(...)

<px:message message="[progress dtbook-to-pef.convert 0-30 text-transform] Translating text to braille"/>
<px:text-transform>
  (...)
</px:text-transform>

<px:message message="[progress dtbook-to-pef.convert 30-90 format-dtbook-as-pef] Formatting DTBook as PEF"/>
<px:format-dtbook-as-pef>
  (...)
</px:format-dtbook-as-pef>

<px:message message="[progress dtbook-to-pef.convert 90-100] Finalizing"/>
<px:whatever>
  (...)
</px:whatever>

</p:declare-step>
```

**Comment by bertfrees** [comment]
This seems like a sound approach. Could you also make it work with messages from XSLT?

**Comment by josteinaj** [comment]
Yes, as long as the messages arrive into the execution log. I'm not sure whether or not they are.

**Comment by bertfrees** [comment]
Problem: the order of messages can be messed up if a step has several inputs and/or contexts for options. In this case it is possible that the steps for computing some inputs are executed after the message step.

Possible solution that Jostein is going to try now: use the `cx:depends-on` attribute to impose the right order. For example:
```xml
<p:identity>
    <p:input port="source">
        <p:pipe step="main" port="source"/>
    </p:input>
</p:identity>
<p:identity cx:depends-on="input-options"/>
<p:identity cx:depends-on="temp-dir"/>
<px:message message="[progress 94 px:dtbook-to-pef.convert] Converting from DTBook to PEF"/>
<px:dtbook-to-pef.convert default-stylesheet="http://www.daisy.org/pipeline/modules/braille/dtbook-to-pef/css/default.css">
    <p:with-option name="temp-dir" select="string(/c:result)">
        <p:pipe step="temp-dir" port="result"/>
    </p:with-option>
    <p:input port="parameters">
        <p:pipe port="result" step="input-options"/>
    </p:input>
</px:dtbook-to-pef.convert>
```

Long-term solution: implement a `cx:message` extension attribute. We'll probably need to patch Calabash for this, but I think it's a rather small change. It's also something generic, useful for others as well, so might be accepted upstream.

**Comment by bertfrees** [comment]
See also https://github.com/ndw/xmlcalabash1/issues/238

**Comment by josteinaj** [comment]
I'm closing this issue since a progress indicator is implemented in the Web UI, and we've established how to declare progress in the scripts: https://github.com/daisy/pipeline-clientlib-java/wiki/Progress-statements
