### ISSUE TITLE
 Make job fail on OutOfMemoryError 

### ISSUE THREAD

**Issue by capitancambio** [daisy/pipeline-issues#446]
If possible, the job should fail, give an error about being out of memory, and probably say what the current Xmx max memory value is.

I've had a hard time finding the root of a bug where the job seemed to be stuck in a "running" state, and no error messages were displayed:
nlbdev/nordic-epub3-dtbook-migrator#285

**Comment by capitancambio** [comment]
https://github.com/daisy/pipeline-framework/pull/82

**Comment by rdeltour** [comment]
Closed by merging daisy/pipeline-framework#82
