### ISSUE TITLE
optimize px:fileset-load (uri normalization and fileset creation)

### ISSUE THREAD

**Issue by josteinaj** [daisy/pipeline-issues#449]
For one of my nordic scripts, 69% of the time were spent inside `px:fileset-load`.

Of course, I might try to reduce the amount of times I invoke it from the nordic scripts, but I think it's worth trying to improve on the performance of `px:fileset-load`.

When running nordic-epub3-to-dtbook with an EPUB containing 32 content files:
 * `px:fileset-load` were invoked 77 times
 * 32% of the time spent in `px:fileset-load` were spent on the for-each that creates the output fileset at the bottom of the script
   * the `px:fileset-add-entry` in the for-each were invoked in total 4448 times and makes up 26% of the total execution time of `px:fileset-load`
     * inside `px:fileset-add-entry`, 58% of the time were spent running the xslt that normalizes URIs. That XSLT were invoked 4672 times
     * inside `px:fileset-add-entry`, the rest of the time were spread relatively evenly. maybe performance could be improved by replacing most of it with an xslt but I'm not sure
 * 25% of the time spent running `px:fileset-load` were spent normalizing URIs. That XSLT were invoked 8385 times
 * In total, this means that 41% of the time in `px:fileset-load` is spent on normalizing URIs, and 29% of the total time spent running nordic-epub3-to-dtbook is spent on normalizing URIs

**Comment by rdeltour** [comment]
Impressive figures, very interesting. I'm not sure I understand why the normalize URI is invoked that many times (8000+ !).
For one thing, we should try to see if the workflow can be updated to lower the number of invocation.
But in any case, this could also mean it's worth implementing all the URI functions in Java as Saxon XPath functions, WDYT ?

**Comment by josteinaj** [comment]
>  I'm not sure I understand why the normalize URI is invoked that many times (8000+ !).

Every time fileset-load is invoked, all in-memory documents get their uris normalized. I don't remember all of the reasons why we normalize URIs in the first place, but could we assume that all hrefs and base URIs in filesets, and all base URIs in in-memory documents, are already normalized? And then only normalize href options and newly loaded documents?

> But in any case, this could also mean it's worth implementing all the URI functions in Java as Saxon XPath functions, WDYT ?

Yeah, I was also wondering about that. It might be a good idea, but if we do so I think we should still fall back to XSLTs when the extensions are not available so that we can run the scripts using pure XProc/XSLT (which is very helpful while developing in oXygen). We can try to reduce the amount of invocations of these XSLTs first, and if we can get it down to 1% of what it's now (or something around that scale), then maybe Java-implementations are not necessary.

The for-each at the end of fileset-load which creates the fileset could possibly be replaced by a single XSLT, maybe that helps the performance (worth a try).

**Comment by rdeltour** [comment]
>> I'm not sure I understand why the normalize URI is invoked that many times (8000+ !).

> Every time fileset-load is invoked, all in-memory documents get their uris normalized. 

Right, but then why is it invoked 8000+ times when there are 32 files in the EPUB ?

> I don't remember all of the reasons why we normalize URIs in the first place

It's basically needed when we do URI comparison. If we do not normalize, we can have issues with e.g. `file:///path/doc.html` vs. `file:/path/doc.html`.

>  but could we assume that all hrefs and base URIs in filesets, and all base URIs in in-memory documents, are already normalized? And then only normalize href options and newly loaded documents?

Yeah, I suppose we can mandate that, but it's putting more responsibility in the hands of the utils lib authors.

>> But in any case, this could also mean it's worth implementing all the URI functions in Java as Saxon XPath functions, WDYT ?

> Yeah, I was also wondering about that. It might be a good idea, but if we do so I think we should still fall back to XSLTs when the extensions are not available so that we can run the scripts using pure XProc/XSLT (which is very helpful while developing in oXygen). We can try to reduce the amount of invocations of these XSLTs first, and if we can get it down to 1% of what it's now (or something around that scale), then maybe Java-implementations are not necessary.

SGTM.

> The for-each at the end of fileset-load which creates the fileset could possibly be replaced by a single XSLT, maybe that helps the performance (worth a try).

yes, may be worth a try.
