### ISSUE TITLE
go-cli: create DP2DATA/dp2 directory if it does not exist

### ISSUE THREAD

**Issue by josteinaj** [daisy/pipeline-issues#460]
If `~/.daisy-pipeline/dp2/` does not exist (Linux, probably same problem with DP2DATA on other platforms), then I get a error about lastid when creating a job:

```
➜  arkiv-test  /home/jostein/Skrivebord/daisy-pipeline-1.9/cli/dp2 nordic-epub3-validate --x-epub /home/jostein/Skrivebord/arkiv-test/innkommende/556844.epub --output /tmp/jobs/validering/result -p
Job 36e1f951-2719-4973-bfae-5d31b9767f1b sent to the server
Error:
	open /home/jostein/.daisy-pipeline/dp2/lastid: no such file or directory
```

The cli should probably create this directory if it is missing (os.MkdirAll) before creating the lastid file:
https://github.com/daisy/pipeline-cli-go/blob/438a2c65fc413f9151595275ed9a2a4a667ff315/cli/scripts.go#L331

**Comment by capitancambio** [comment]
Done in https://github.com/daisy/pipeline-cli-go/tree/issues/460
