### ISSUE TITLE
only some scripts appear when starting gui

### ISSUE THREAD

**Issue by josteinaj** [daisy/pipeline-issues#466]
Not sure what triggers this issue and it might be with the framework, not the gui itself. If I restart the gui it works fine again. Here's a log file, not sure if it contains anything useful though:

https://gist.github.com/josteinaj/62a4d5ea24735a6e4ea2

@marisademeglio assigning to you since I'm experiencing this with the gui.

**Comment by marisademeglio** [comment]
yeah @rdeltour noticed this too. it only happens to me sometimes. i think it's a problem with the startup order. @capitancambio any ideas?

**Comment by capitancambio** [comment]
Hum, this is weird. we could try to change the gui loading priority, but
the scripts should load eventually, do you load the scripts once at startup
or you listen for them?

cheers,

Javi

**Comment by marisademeglio** [comment]
At startup, we get the scriptregistry, and the GUI doesn't launch until that dependency is satisfied. Then immediately upon launch, we get a list of scripts once. We don't listen for them to change.

**Comment by marisademeglio** [comment]
Maybe the ScriptRegistry is available as a service before the scripts have been loaded. If this is the problem, we either need to change this so it's not available until it's been populated, or have an event issued when they're done loading. I can check along the way for new scripts but it would look weird to users to have the scripts list look different the first few times they click the drop down.

**Comment by marisademeglio** [comment]
Decision: try loading the GUI last (lowest priority). Then look into subscribing to script services.

**Comment by capitancambio** [comment]
https://github.com/daisy/pipeline-gui/pull/44
