### ISSUE TITLE
don't preserve whitespace for port metadata

### ISSUE THREAD

**Issue by marisademeglio** [daisy/pipeline-issues#467]
E.g.

![screen shot 2015-06-04 at 5 15 15 pm](https://cloud.githubusercontent.com/assets/734730/7997129/50a37748-0add-11e5-9499-fecea6b2f586.png)

(Sorry for the screenshot instead of text; the github markdown parser strips whitespace out of code!)

Can we parse this without preserving whitespace? It doesn't look right in the GUI. I could try to clean it up but I'd rather have the XML parser do it automatically.

@capitancambio what do you think?

**Comment by capitancambio** [comment]
Not sure I get it, could you give a example (the xmls involved) plz?

cheers,

Javi

**Comment by capitancambio** [comment]
The image wasn't shown in the email. I still don't get it tough :joy:, is there a new line that breaks the how the documentation is displayed in the gui?

**Comment by marisademeglio** [comment]
Well I can strip out linebreaks and tabs but the extra whitespace still comes through. So if there are 15 spaces in the documentation string, it shows up in the gui.

**Comment by josteinaj** [comment]
Maybe the framework could invoke the XPath function `normalize-uri` on all the port/option metadata?

Or match the regex `\s+` and replace with a single whitespace + strip preceding and trailing spaces?

**Comment by josteinaj** [comment]
Sorry, I meant `normalize-space`, not `normalize-uri`.

**Comment by capitancambio** [comment]
https://github.com/daisy/pipeline-framework/pull/91
