### ISSUE TITLE
No 'class' in configuration for px:break-detect

### ISSUE THREAD

**Issue by josteinaj** [daisy/pipeline-issues#480]
Occured in Pipeline 2 v1.9 on Linux when running DTBook to DAISY 3 with TTS.

CC @larsvoigt

**Comment by larsvoigt** [comment]
Thank you @josteinaj. 

```
java -version
openjdk version "1.8.0_91"
OpenJDK Runtime Environment (build 1.8.0_91-8u91-b14-3ubuntu1~16.04.1-b14)
OpenJDK 64-Bit Server VM (build 25.91-b14, mixed mode)
```

**Comment by josteinaj** [comment]
Ah, I think there's an issue with Java 8 and DP2 v1.9. Could you try Java 7?

**Comment by larsvoigt** [comment]
Okay @josteinaj you are right. It depends on which java version will be used.
For my setup: with the Java 7 version from oracle works fine for me.
```
java -version
java version "1.7.0_80"
Java(TM) SE Runtime Environment (build 1.7.0_80-b15)
Java HotSpot(TM) 64-Bit Server VM (build 24.80-b11, mixed mode)
```

**Comment by josteinaj** [comment]
That's great. Could we close the issue then or do you think it's still an issue?

**Comment by larsvoigt** [comment]
I´m fine. You can close this issuse.

**Comment by josteinaj** [comment]
Great. :)

**Comment by larsvoigt** [comment]
Maybe we need to open another generally issue of running DP2 with java 8?

**Comment by josteinaj** [comment]
The next version of DP2 will require Java 8, so we don't need a new issue.

**Comment by larsvoigt** [comment]
:+1:
